// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['consoleService']['Close']();
}

export function LoopRead() {
  return window['go']['main']['consoleService']['LoopRead']();
}

export function Resize(arg1, arg2) {
  return window['go']['main']['consoleService']['Resize'](arg1, arg2);
}

export function SendText(arg1) {
  return window['go']['main']['consoleService']['SendText'](arg1);
}
