// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function LoopRead():Promise<void>;

export function Resize(arg1:number,arg2:number):Promise<void>;

export function SendText(arg1:string):Promise<void>;
